version: 2

defaults: &defaults
  working_directory: /home/circleci/microcosm
  docker:
    - image: circleci/node:8.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run: yarn bootstrap
      - run: sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - microcosm
  audit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: yarn flow
      - run: yarn lint
  website:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: ./bin/deploy
  test-dev:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: yarn test:cov --ci
      - run: yarn report-coverage
  test-prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: yarn test:prod --ci

workflows:
  version: 2
  microcosm:
    jobs:
      - build
      - website
      - audit:
          requires:
            - build
      - test-dev:
          requires:
            - build
      - test-prod:
          requires:
            - build
